name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Java sandbox image
        run: |
          docker build -t docker.bedson.tech/codeftc-java-sandbox:latest \
            -f docker/java-sandbox/Dockerfile .

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test tests/
